name: Bug report
description: Something else is wrong
labels: [bug]
body:
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected and actual behaviour
    validations:
      required: true
  - type: input
    id: env
    attributes:
      label: Browser, OS and controller
    validations:
      required: true
  - type: textarea
    id: console
    attributes:
      label: Browser console errors
      render: text
